"use client";
/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/set-state-in-effect, @next/next/no-html-link-for-pages */
import { useEffect, useState } from "react";
import "../account/account.css";

export default function GlobalAdminPage() {
  const [data,setData]=useState<any>({}); const [error,setError]=useState("");
  const load=async()=>{const names=["users","token-transactions","payments","settings"];const rs=await Promise.all(names.map(x=>fetch(`/api/admin/${x}`)));if(rs.some(x=>!x.ok))throw new Error("Требуются права global admin.");setData(Object.assign({},...await Promise.all(rs.map(x=>x.json()))));};
  useEffect(()=>{void load().catch(e=>setError(e.message));},[]);
  const save=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=new FormData(e.currentTarget);const response=await fetch("/api/admin/settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({token_exchange_rate:Number(form.get("rate")),brutto_coefficient:Number(form.get("brutto"))})});if(!response.ok)setError((await response.json()).error);else await load();};
  const transfer=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=new FormData(e.currentTarget);const response=await fetch("/api/admin/tokens/transfer",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({sourceUserId:form.get("source"),targetUserId:form.get("target"),amount:Number(form.get("amount")),reason:form.get("reason")})});if(!response.ok)setError((await response.json()).error);else await load();};
  return <main className="account-shell"><aside><a className="logo" href="/">ROOM <span>admin</span></a><nav>{["Users","Token balances","Token transfers","Token history","Tariffs","Token packages","Payments","AI Netto / Brutto","Global settings","Tenants","Audit log"].map((x,i)=><a key={x} href={`#a${i}`}>{x}</a>)}</nav><a href="/account">Личный кабинет</a></aside><div className="account-content"><header><small>GLOBAL ADMIN</small><h1>Управление Room Design</h1><p>Глобальные настройки, пользователи, токены и платежи.</p></header>{error&&<p className="alert">{error}</p>}
  <section id="a0" className="panel"><h2>Users & token balances</h2><div className="list">{data.users?.map((x:any)=><p key={x.id}><span>{x.email}<small>{x.global_role}</small></span><b>{Number(x.token_balance).toLocaleString("ru-RU")}</b></p>)}</div></section>
  <section id="a2" className="panel"><h2>Token transfer</h2><form className="buy" onSubmit={transfer}><select name="source" required>{data.users?.map((x:any)=><option key={x.id} value={x.id}>{x.email} ({x.token_balance})</option>)}</select><select name="target" required>{data.users?.map((x:any)=><option key={x.id} value={x.id}>{x.email}</option>)}</select><input name="amount" type="number" min="1" required placeholder="Tokens"/><input name="reason" placeholder="Reason"/><button>Перевести</button></form></section>
  <section id="a8" className="panel"><h2>Global settings</h2>{data.settings&&<form className="buy" onSubmit={save}><label>Tokens / RUB <input name="rate" type="number" min="1" defaultValue={data.settings.token_exchange_rate}/></label><label>Brutto coefficient <input name="brutto" type="number" min="0.01" step="0.01" defaultValue={data.settings.brutto_coefficient}/></label><button>Сохранить</button></form>}</section>
  <section id="a3" className="panel"><h2>Token history</h2><div className="list">{data.transactions?.map((x:any)=><p key={x.id}><span>{x.email} · {x.type}<small>{x.description}</small></span><b>{Number(x.amount).toLocaleString("ru-RU")}</b></p>)}</div></section>
  <section id="a6" className="panel"><h2>Payments</h2><div className="list">{data.payments?.map((x:any)=><p key={x.id}><span>{x.email} · {x.status}<small>rate snapshot: {x.exchange_rate_snapshot}</small></span><b>{(x.amount/100).toLocaleString("ru-RU")} {x.currency}</b></p>)}</div></section>
  </div></main>;
}
