import assert from "node:assert/strict";
import test from "node:test";
import { runItTurn } from "../lib/it/core.ts";
import { ROOM_DESIGN_PRODUCT_KNOWLEDGE } from "../lib/it/product-knowledge.ts";

const context = {
  route: "#студия",
  projectId: "project-1",
  projectName: "Гостиная",
  section: "image-editor",
  activeTool: "Добавить мебель",
  furnitureAction: "add",
  selectedObject: null,
  render: { hasSource: true, hasResult: false, isGenerating: false },
  planogram: { itemCount: 0, selectedItemId: null },
  availableActions: ["navigate_to", "focus_element", "highlight_element", "search_catalog"],
};

const products = [
  { id: "chair-1", name: "Кресло Uno", image: "https://example.com/1.jpg", url: "https://example.com/1", price: 129_000, category: "Кресла", color: "Серый", material: "Шенилл", widthMm: 810, depthMm: 760, heightMm: 720 },
  { id: "chair-2", name: "Кресло Due", image: "https://example.com/2.jpg", url: "https://example.com/2", price: 139_000, category: "Кресла", color: "Оливковый", material: "Рогожка", widthMm: 760, depthMm: 720, heightMm: 780 },
];

const modelAdapter = (calls, response = "Естественный ответ модели.") => async (input) => {
  calls.push(input);
  return response;
};

test("every normal answer is generated by the conversation model", async () => {
  const calls = [];
  const turn = await runItTurn(
    { message: "Мне здесь как-то холодно. Что изменить?", context },
    { searchCatalog: async () => [], answerConversation: modelAdapter(calls, "Добавьте тёплое дерево и свет 2700–3000 K.") },
  );
  assert.equal(calls.length, 1);
  assert.match(turn.text, /тёплое дерево/);
  assert.equal(calls[0].context.projectId, context.projectId);
});

test("an attached room image is forwarded to the multimodal conversation model", async () => {
  const calls = [];
  const image = "data:image/png;base64,AAAA";
  await runItTurn(
    { message: "Что улучшить в этой комнате?", image, context },
    { searchCatalog: async () => [], answerConversation: modelAdapter(calls) },
  );
  assert.equal(calls[0].image, image);
});

test("Replace stays text-only while its final text comes from the model", async () => {
  const calls = [];
  const turn = await runItTurn(
    { message: "Как заменить диван?", context },
    { searchCatalog: async () => [], answerConversation: modelAdapter(calls, "Откройте редактор изображений и нажмите «Заменить».") },
  );
  assert.equal(turn.text, "Откройте редактор изображений и нажмите «Заменить».");
  assert.equal(turn.actions, undefined);
  assert.match(calls[0].toolFacts.join(" "), /только текстом/);
});

test("a short follow-up retains Replace context", async () => {
  const calls = [];
  const history = [
    { role: "user", text: "Как заменить диван?" },
    { role: "assistant", text: "Могу показать кнопку." },
  ];
  const turn = await runItTurn(
    { message: "Покажи.", context, history },
    { searchCatalog: async () => [], answerConversation: modelAdapter(calls, "Показываю.") },
  );
  assert.equal(calls[0].history.length, 2);
  assert.equal(turn.actions, undefined);
  assert.match(calls[0].toolFacts.join(" "), /нажать «Заменить»/);
});

test("another-item follow-up inherits the furniture subject and searches catalog", async () => {
  let searchInput;
  const history = [
    { role: "user", text: "Как заменить диван?" },
    { role: "assistant", text: "Показываю кнопку. После выбора можно подобрать другой диван." },
  ];
  const turn = await runItTurn(
    { message: "А теперь хочу другой.", context, history },
    {
      searchCatalog: async (input) => { searchInput = input; return products.map((item) => ({ ...item, category: "Диваны", name: item.name.replace("Кресло", "Диван") })); },
      answerConversation: async () => "Подобрало два реальных варианта дивана.",
    },
  );
  assert.equal(searchInput.category, "sofa");
  assert.equal(turn.products?.length, 2);
});

test("multi-intent stays text-only and lets the model answer the full question", async () => {
  const calls = [];
  const message = "Как заменить диван и какой цвет сюда лучше поставить?";
  const turn = await runItTurn(
    { message, context },
    { searchCatalog: async () => [], answerConversation: modelAdapter(calls, "Показываю Replace. По цвету попробуйте глубокий оливковый.") },
  );
  assert.equal(turn.actions, undefined);
  assert.equal(calls[0].message, message);
  assert.match(turn.text, /Replace.*оливковый/);
});

test("catalog search returns real products and model-generated copy", async () => {
  const calls = [];
  let searchInput;
  const turn = await runItTurn(
    { message: "Найди кресло до 150 тысяч ₽", context },
    {
      searchCatalog: async (input) => { searchInput = input; return products; },
      answerConversation: modelAdapter(calls, "Нашло два варианта. Второе выглядит легче из-за более компактной ширины."),
    },
  );
  assert.equal(searchInput.category, "armchair");
  assert.equal(searchInput.maxPrice, 150_000);
  assert.equal(calls[0].products.length, 2);
  assert.deepEqual(turn.products, products);
});

test("showing available sofas under a budget triggers a cheapest-first catalog search", async () => {
  let searchInput;
  await runItTurn(
    { message: "Самые дешёвые диваны до 500 тыс покажи, только в наличии", context },
    {
      searchCatalog: async (input) => { searchInput = input; return []; },
      answerConversation: async () => "Подходящих диванов не найдено.",
    },
  );
  assert.equal(searchInput.category, "sofa");
  assert.equal(searchInput.maxPrice, 500_000);
});

test("planogram guidance explains the real navigation button without UI actions", async () => {
  const calls = [];
  const turn = await runItTurn(
    { message: "Что нажать, чтобы попасть в планограмму?", context },
    { searchCatalog: async () => [], answerConversation: modelAdapter(calls, "Нажмите «Создание интерьера» слева.") },
  );
  assert.equal(turn.actions, undefined);
  assert.match(calls[0].toolFacts.join(" "), /только текстом/);
  assert.match(turn.text, /Создание интерьера/);
});

test("planogram follow-up explains the sofa control without UI actions", async () => {
  const calls = [];
  const planogramContext = { ...context, section: "planogram", activeTool: "Планограмма" };
  const history = [{ role: "user", text: "Как добавить диван и кресло?" }];
  const turn = await runItTurn(
    { message: "На план", context: planogramContext, history },
    { searchCatalog: async () => [], answerConversation: modelAdapter(calls, "Нажмите кнопку «Диван» справа.") },
  );
  assert.equal(turn.actions, undefined);
  assert.match(calls[0].toolFacts.join(" "), /Кнопка «Диван»/);
});

test("a selected planogram item exposes exact editing and reference instructions without asking for a screenshot", async () => {
  const calls = [];
  const selectedContext = {
    ...context,
    section: "planogram",
    activeTool: "Планограмма",
    planogram: {
      itemCount: 1,
      selectedItemId: "chair-1",
      selectedItem: { id: "chair-1", name: "Кресло", kind: "chair", widthMm: 800, depthMm: 800, rotation: 0, hasReference: false, referenceName: null },
      room: { widthMm: 6000, lengthMm: 4500 },
      hasFloorReference: false,
      hasWallReference: false,
      hasCamera: false,
    },
    workspace: { isAuthenticated: true, projectSaved: false, historyCount: 0, queuedEditCount: 0, hasFurnitureReference: false },
  };
  const turn = await runItTurn(
    { message: "Как кресло, которое добавил в планограмму, отредактировать и заменить изображение?", context: selectedContext },
    { searchCatalog: async () => [], answerConversation: modelAdapter(calls, "Нажмите по креслу правой кнопкой и выберите «Загрузить референс».") },
  );
  assert.equal(turn.actions, undefined);
  assert.match(calls[0].toolFacts.join(" "), /правой кнопкой/);
  assert.match(calls[0].toolFacts.join(" "), /800 × 800/);
  assert.match(calls[0].toolFacts.join(" "), /Скриншот для этого не нужен/);
});

test("an unselected planogram item still gets text-only editing guidance", async () => {
  const calls = [];
  const planogramContext = {
    ...context,
    section: "planogram",
    activeTool: "Планограмма",
    planogram: { itemCount: 1, selectedItemId: null, selectedItem: null, room: { widthMm: 6000, lengthMm: 4500 }, hasFloorReference: false, hasWallReference: false, hasCamera: false },
    workspace: { isAuthenticated: true, projectSaved: false, historyCount: 0, queuedEditCount: 0, hasFurnitureReference: false },
  };
  const turn = await runItTurn(
    { message: "Как мне отредактировать кресло и заменить его изображение?", context: planogramContext },
    { searchCatalog: async () => [], answerConversation: modelAdapter(calls, "Сначала нажмите на кресло." ) },
  );
  assert.equal(turn.actions, undefined);
  assert.match(calls[0].toolFacts.join(" "), /сейчас не выделен/);
  assert.match(calls[0].toolFacts.join(" "), /скриншот не нужен/);
});

test("planogram surface references and save point to their own controls", async () => {
  const floorCalls = [];
  const saveCalls = [];
  const planogramContext = {
    ...context,
    section: "planogram",
    activeTool: "Планограмма",
    planogram: { itemCount: 1, selectedItemId: null, selectedItem: null, room: { widthMm: 6000, lengthMm: 4500 }, hasFloorReference: false, hasWallReference: false, hasCamera: false },
    workspace: { isAuthenticated: true, projectSaved: false, historyCount: 0, queuedEditCount: 0, hasFurnitureReference: false },
  };
  const floor = await runItTurn(
    { message: "Как добавить референс пола?", context: planogramContext },
    { searchCatalog: async () => [], answerConversation: modelAdapter(floorCalls, "Нажмите кнопку пола.") },
  );
  const save = await runItTurn(
    { message: "Что делает кнопка Сохранить проект в планограмме?", context: planogramContext },
    { searchCatalog: async () => [], answerConversation: modelAdapter(saveCalls, "Она сохраняет план в проекте аккаунта.") },
  );
  assert.equal(floor.actions, undefined);
  assert.equal(save.actions, undefined);
  assert.match(floorCalls[0].toolFacts.join(" "), /Референс пола/);
  assert.match(saveCalls[0].toolFacts.join(" "), /проекте аккаунта/);
  assert.match(saveCalls[0].toolFacts.join(" "), /JSON-файл не скачивается/);
});

test("the verified product knowledge covers both editors and known limitations", () => {
  assert.match(ROOM_DESIGN_PRODUCT_KNOWLEDGE.planogram.reference, /правой кнопкой/);
  assert.match(ROOM_DESIGN_PRODUCT_KNOWLEDGE.planogram.catalogReference, /Добавить из каталога/);
  assert.match(ROOM_DESIGN_PRODUCT_KNOWLEDGE.planogram.camera, /двойной клик/i);
  assert.match(ROOM_DESIGN_PRODUCT_KNOWLEDGE.imageEditor.replace, /поставить точку/i);
  assert.match(ROOM_DESIGN_PRODUCT_KNOWLEDGE.commercialProposal.download, /Скачать PDF/);
  assert.match(ROOM_DESIGN_PRODUCT_KNOWLEDGE.commercialProposal.download, /Скачать PPT/);
  assert.match(ROOM_DESIGN_PRODUCT_KNOWLEDGE.commercialProposal.formats, /PowerPoint/);
  assert.match(ROOM_DESIGN_PRODUCT_KNOWLEDGE.imageEditor.material, /Каталог материалов пока не готов/);
  assert.match(ROOM_DESIGN_PRODUCT_KNOWLEDGE.assistant.safety, /только текстом/);
  assert.match(ROOM_DESIGN_PRODUCT_KNOWLEDGE.assistant.safety, /не перемещается/);
});

test("commercial proposal guidance states the exact editor flow and both export formats", async () => {
  const calls = [];
  const turn = await runItTurn(
    { message: "Как скачать коммерческое предложение в PowerPoint?", context },
    { searchCatalog: async () => [], answerConversation: modelAdapter(calls, "Откройте редактор предложения и нажмите «Скачать PPT» для PowerPoint.") },
  );
  assert.equal(turn.actions, undefined);
  assert.match(calls[0].toolFacts.join(" "), /Скачать PDF/);
  assert.match(calls[0].toolFacts.join(" "), /Скачать PPT/);
  assert.match(calls[0].toolFacts.join(" "), /PowerPoint в формате PPTX/);
  assert.match(calls[0].toolFacts.join(" "), /Скриншот для этого не нужен/);
});

test("current visualization download guidance names the real WebP format", async () => {
  const calls = [];
  await runItTurn(
    { message: "Как скачать текущую визуализацию?", context },
    { searchCatalog: async () => [], answerConversation: modelAdapter(calls) },
  );
  assert.match(calls[0].toolFacts.join(" "), /WebP/);
  assert.match(calls[0].toolFacts.join(" "), /истории рендеров/);
});

test("cheaper follow-up inherits product category and budget from history", async () => {
  const calls = [];
  let searchInput;
  const history = [
    { role: "user", text: "Найди кресло до 150 тысяч" },
    { role: "assistant", text: "Вот два варианта.", products },
  ];
  await runItTurn(
    { message: "Нет, подешевле.", context, history },
    {
      searchCatalog: async (input) => { searchInput = input; return [products[0]]; },
      answerConversation: modelAdapter(calls),
    },
  );
  assert.equal(searchInput.category, "armchair");
  assert.equal(searchInput.maxPrice, 128_999);
  assert.equal(calls[0].history[1].products.length, 2);
});

test("out-of-scope wording is decided by the semantic model", async () => {
  const calls = [];
  const turn = await runItTurn(
    { message: "Какая завтра погода?", context },
    { searchCatalog: async () => [], answerConversation: modelAdapter(calls, "Я помогаю с Room Design, интерьером и архитектурой.") },
  );
  assert.equal(calls.length, 1);
  assert.match(turn.text, /Room Design/);
});

test("history is capped to the latest 12 messages", async () => {
  const calls = [];
  const history = Array.from({ length: 18 }, (_, index) => ({ role: index % 2 ? "assistant" : "user", text: `turn-${index}` }));
  await runItTurn(
    { message: "Почему?", context, history },
    { searchCatalog: async () => [], answerConversation: modelAdapter(calls) },
  );
  assert.equal(calls[0].history.length, 12);
  assert.equal(calls[0].history[0].text, "turn-6");
});

test("provider failure returns a technical error instead of a canned FAQ answer", async () => {
  const turn = await runItTurn(
    { message: "Что бы ты добавил?", context },
    { searchCatalog: async () => [], answerConversation: async () => null },
  );
  assert.equal(turn.state, "error");
  assert.match(turn.text, /модель временно недоступна/);
});
