import assert from "node:assert/strict";
import test from "node:test";
import { runItTurn } from "../lib/it/core.ts";

const context = {
  route: "#студия",
  projectId: "project-1",
  projectName: "Гостиная",
  section: "image-editor",
  activeTool: "Добавить мебель",
  furnitureAction: "add",
  selectedObject: null,
  render: { hasSource: true, hasResult: false, isGenerating: false },
  planogram: { itemCount: 0, selectedItemId: null },
  availableActions: ["navigate_to", "focus_element", "highlight_element", "search_catalog"],
};

const products = [
  { id: "chair-1", name: "Кресло Uno", image: "https://example.com/1.jpg", url: "https://example.com/1", price: 129_000, category: "Кресла", color: "Серый", material: "Шенилл", widthMm: 810, depthMm: 760, heightMm: 720 },
  { id: "chair-2", name: "Кресло Due", image: "https://example.com/2.jpg", url: "https://example.com/2", price: 139_000, category: "Кресла", color: "Оливковый", material: "Рогожка", widthMm: 760, depthMm: 720, heightMm: 780 },
];

const modelAdapter = (calls, response = "Естественный ответ модели.") => async (input) => {
  calls.push(input);
  return response;
};

test("every normal answer is generated by the conversation model", async () => {
  const calls = [];
  const turn = await runItTurn(
    { message: "Мне здесь как-то холодно. Что изменить?", context },
    { searchCatalog: async () => [], answerConversation: modelAdapter(calls, "Добавьте тёплое дерево и свет 2700–3000 K.") },
  );
  assert.equal(calls.length, 1);
  assert.match(turn.text, /тёплое дерево/);
  assert.equal(calls[0].context.projectId, context.projectId);
});

test("Replace uses tools but its final text still comes from the model", async () => {
  const calls = [];
  const turn = await runItTurn(
    { message: "Как заменить диван?", context },
    { searchCatalog: async () => [], answerConversation: modelAdapter(calls, "Да, можно. Показываю кнопку «Заменить».") },
  );
  assert.equal(turn.text, "Да, можно. Показываю кнопку «Заменить».");
  assert.deepEqual(turn.actions?.map((action) => action.type), ["navigate", "focus", "highlight"]);
  assert.match(calls[0].toolFacts.join(" "), /подсветка кнопки/);
});

test("a short follow-up retains Replace context", async () => {
  const calls = [];
  const history = [
    { role: "user", text: "Как заменить диван?" },
    { role: "assistant", text: "Могу показать кнопку." },
  ];
  const turn = await runItTurn(
    { message: "Покажи.", context, history },
    { searchCatalog: async () => [], answerConversation: modelAdapter(calls, "Показываю.") },
  );
  assert.equal(calls[0].history.length, 2);
  assert.equal(turn.actions?.some((action) => action.type === "highlight"), true);
});

test("another-item follow-up inherits the furniture subject and searches catalog", async () => {
  let searchInput;
  const history = [
    { role: "user", text: "Как заменить диван?" },
    { role: "assistant", text: "Показываю кнопку. После выбора можно подобрать другой диван." },
  ];
  const turn = await runItTurn(
    { message: "А теперь хочу другой.", context, history },
    {
      searchCatalog: async (input) => { searchInput = input; return products.map((item) => ({ ...item, category: "Диваны", name: item.name.replace("Кресло", "Диван") })); },
      answerConversation: async () => "Подобрало два реальных варианта дивана.",
    },
  );
  assert.equal(searchInput.category, "sofa");
  assert.equal(turn.products?.length, 2);
});

test("multi-intent keeps UI action and lets the model answer the full question", async () => {
  const calls = [];
  const message = "Как заменить диван и какой цвет сюда лучше поставить?";
  const turn = await runItTurn(
    { message, context },
    { searchCatalog: async () => [], answerConversation: modelAdapter(calls, "Показываю Replace. По цвету попробуйте глубокий оливковый.") },
  );
  assert.ok(turn.actions?.length);
  assert.equal(calls[0].message, message);
  assert.match(turn.text, /Replace.*оливковый/);
});

test("catalog search returns real products and model-generated copy", async () => {
  const calls = [];
  let searchInput;
  const turn = await runItTurn(
    { message: "Найди кресло до 150 тысяч ₽", context },
    {
      searchCatalog: async (input) => { searchInput = input; return products; },
      answerConversation: modelAdapter(calls, "Нашло два варианта. Второе выглядит легче из-за более компактной ширины."),
    },
  );
  assert.equal(searchInput.category, "armchair");
  assert.equal(searchInput.maxPrice, 150_000);
  assert.equal(calls[0].products.length, 2);
  assert.deepEqual(turn.products, products);
});

test("cheaper follow-up inherits product category and budget from history", async () => {
  const calls = [];
  let searchInput;
  const history = [
    { role: "user", text: "Найди кресло до 150 тысяч" },
    { role: "assistant", text: "Вот два варианта.", products },
  ];
  await runItTurn(
    { message: "Нет, подешевле.", context, history },
    {
      searchCatalog: async (input) => { searchInput = input; return [products[0]]; },
      answerConversation: modelAdapter(calls),
    },
  );
  assert.equal(searchInput.category, "armchair");
  assert.equal(searchInput.maxPrice, 128_999);
  assert.equal(calls[0].history[1].products.length, 2);
});

test("out-of-scope wording is decided by the semantic model", async () => {
  const calls = [];
  const turn = await runItTurn(
    { message: "Какая завтра погода?", context },
    { searchCatalog: async () => [], answerConversation: modelAdapter(calls, "Я помогаю с Room Design, интерьером и архитектурой.") },
  );
  assert.equal(calls.length, 1);
  assert.match(turn.text, /Room Design/);
});

test("history is capped to the latest 12 messages", async () => {
  const calls = [];
  const history = Array.from({ length: 18 }, (_, index) => ({ role: index % 2 ? "assistant" : "user", text: `turn-${index}` }));
  await runItTurn(
    { message: "Почему?", context, history },
    { searchCatalog: async () => [], answerConversation: modelAdapter(calls) },
  );
  assert.equal(calls[0].history.length, 12);
  assert.equal(calls[0].history[0].text, "turn-6");
});

test("provider failure returns a technical error instead of a canned FAQ answer", async () => {
  const turn = await runItTurn(
    { message: "Что бы ты добавил?", context },
    { searchCatalog: async () => [], answerConversation: async () => null },
  );
  assert.equal(turn.state, "error");
  assert.match(turn.text, /модель временно недоступна/);
});
